aliases:
  - &restore-yarn-cache
    restore_cache:
      name: Restoring cache
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - &save-yarn-cache
    save_cache:
      name: Saving cache
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  - &install-yarn-dependencies
    run:
      name: Installing Yarn dependencies
      command: yarn install

defaults: &defaults
  docker:
    - image: circleci/node:8.11.1
  working_directory: ~/repo

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore-yarn-cache
      - *install-yarn-dependencies
      - *save-yarn-cache
      - run:
          name: Running tests
          command: yarn run test

workflows:
  version: 2
  test:
    jobs:
      - test
